In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create DataFrame with missing values
df = pd.DataFrame({
    'P': [5, 8, np.nan, 12, 20],
    'Q': [100, np.nan, np.nan, 400, 500],
    'R': ['red', 'blue', 'green', np.nan, 'black']
})
print('Original with NaN:')
print(df)

Original with NaN:
      P      Q      R
0   5.0  100.0    red
1   8.0    NaN   blue
2   NaN    NaN  green
3  12.0  400.0    NaN
4  20.0  500.0  black

In [3]:
print('\n=== Detect Missing ===')
print(df.isnull())

=== Detect Missing ===
       P      Q      R
0  False  False  False
1  False   True  False
2   True   True  False
3  False  False   True
4  False  False  False

In [4]:
print(df.isnull().sum())

P    1
Q    2
R    1
dtype: int64

In [5]:
df.isnull().sum().sum()

np.int64(4)

In [6]:
print(df.notnull())

       P      Q      R
0   True   True   True
1   True  False   True
2  False  False   True
3   True   True  False
4   True   True   True

In [7]:
print(df.dropna())

      P      Q      R
0   5.0  100.0    red
4  20.0  500.0  black

In [8]:
print(df.dropna(axis=1))

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [9]:
print(df.dropna(how='all'))

      P      Q      R
0   5.0  100.0    red
1   8.0    NaN   blue
2   NaN    NaN  green
3  12.0  400.0    NaN
4  20.0  500.0  black

In [10]:
print(df.dropna(thresh=2))

      P      Q      R
0   5.0  100.0    red
1   8.0    NaN   blue
3  12.0  400.0    NaN
4  20.0  500.0  black

In [11]:
print(df.fillna(0))

      P      Q      R
0   5.0  100.0    red
1   8.0    0.0   blue
2   0.0    0.0  green
3  12.0  400.0      0
4  20.0  500.0  black

In [12]:
print(df['P'].fillna(df['P'].mean()))

0     5.00
1     8.00
2    11.25
3    12.00
4    20.00
Name: P, dtype: float64

In [13]:
print(df.ffill())

      P      Q      R
0   5.0  100.0    red
1   8.0  100.0   blue
2   8.0  100.0  green
3  12.0  400.0  green
4  20.0  500.0  black

In [14]:
print(df.bfill())

      P      Q      R
0   5.0  100.0    red
1   8.0  400.0   blue
2  12.0  400.0  green
3  12.0  400.0  black
4  20.0  500.0  black

In [15]:
print(df[['P', 'Q']].interpolate())

      P      Q
0   5.0  100.0
1   8.0  200.0
2  10.0  300.0
3  12.0  400.0
4  20.0  500.0

In [16]:
print(df.replace(np.nan, 'MISSING'))

         P        Q        R
0      5.0    100.0      red
1      8.0  MISSING     blue
2  MISSING  MISSING    green
3     12.0    400.0  MISSING
4     20.0    500.0    black

In [17]:
print(df.replace({np.nan: 0, 'red': 'RED', 'blue': 'BLUE'}))

      P      Q      R
0   5.0  100.0    RED
1   8.0    0.0   BLUE
2   0.0    0.0  green
3  12.0  400.0      0
4  20.0  500.0  black

In [18]:
np.random.seed(11)
df = pd.DataFrame(np.random.randint(1, 100, (5, 4)), columns=['W', 'X', 'Y', 'Z'])
print('DataFrame:')
print(df)

DataFrame:
    W   X   Y   Z
0  26  64  81  92
1  82  56  14  77
2  34  72  83  25
3  93  49  33  46
4   5  35  13   2

In [19]:
print(df.sum())

W    240
X    276
Y    224
Z    242
dtype: int64

In [20]:
print(df.mean())

W    48.0
X    55.2
Y    44.8
Z    48.4
dtype: float64

In [21]:
print(df.std())

W    37.782271
X    14.202113
Y    34.888393
Z    36.827978
dtype: float64

In [22]:
print('Min:', df.min().to_dict())
print('Max:', df.max().to_dict())

Min: {'W': 5, 'X': 35, 'Y': 13, 'Z': 2}
Max: {'W': 93, 'X': 72, 'Y': 83, 'Z': 92}

In [23]:
print('Cumulative sum:')
print(df.cumsum())
print('\nCumulative product:')
print(df.cumprod())

Cumulative sum:
     W    X    Y    Z
0   26   64   81   92
1  108  120   95  169
2  142  192  178  194
3  235  241  211  240
4  240  276  224  242

Cumulative product:
          W          X         Y         Z
0        26         64        81        92
1      2132       3584      1134      7084
2     72488     258048     94122    177100
3   6741384   12644352   3106026   8146600
4  33706920  442552320  40378338  16293200

In [24]:
print('\nPercent change:')
print(df.pct_change())

Percent change:
          W         X         Y         Z
0       NaN       NaN       NaN       NaN
1  2.153846 -0.125000 -0.827160 -0.163043
2 -0.585366  0.285714  4.928571 -0.675325
3  1.735294 -0.319444 -0.602410  0.840000
4 -0.946237 -0.285714 -0.606061 -0.956522

In [25]:
print('\nDifference:')
print(df.diff())

Difference:
      W     X     Y     Z
0   NaN   NaN   NaN   NaN
1  56.0  -8.0 -67.0 -15.0
2 -48.0  16.0  69.0 -52.0
3  59.0 -23.0 -50.0  21.0
4 -88.0 -14.0 -20.0 -44.0

In [26]:
print('\nRound to 1 decimal:')
print((df / 4).round(1))

Round to 1 decimal:
      W     X     Y     Z
0   6.5  16.0  20.2  23.0
1  20.5  14.0   3.5  19.2
2   8.5  18.0  20.8   6.2
3  23.2  12.2   8.2  11.5
4   1.2   8.8   3.2   0.5

In [27]:
print('\nAbsolute:')
print((df - 50).abs())

Absolute:
    W   X   Y   Z
0  24  14  31  42
1  32   6  36  27
2  16  22  33  25
3  43   1  17   4
4  45  15  37  48

In [28]:
print('\nClip to [15, 85]:')
print(df.clip(15, 85))

Clip to [15, 85]:
    W   X   Y   Z
0  26  64  81  85
1  82  56  15  77
2  34  72  83  25
3  85  49  33  46
4  15  35  15  15

In [29]:
print('\n=== Row-wise operations ===')
print('Sum axis=1:', df.sum(axis=1).to_dict())
print('Mean axis=1:', df.mean(axis=1).to_dict())

=== Row-wise operations ===
Sum axis=1: {0: 263, 1: 229, 2: 214, 3: 221, 4: 55}
Mean axis=1: {0: 65.75, 1: 57.25, 2: 53.5, 3: 55.25, 4: 13.75}

In [30]:
print('Correlation:')
print(df.corr())
print('\nCovariance:')
print(df.cov())

Correlation:
          W         X         Y         Z
W  1.000000  0.087590 -0.292453  0.400303
X  0.087590  1.000000  0.833117  0.461537
Y -0.292453  0.833117  1.000000  0.254384
Z  0.400303  0.461537  0.254384  1.000000

Covariance:
        W      X        Y        Z
W  1427.5   47.0  -385.50   557.00
X    47.0  201.7   412.80   241.40
Y  -385.5  412.8  1217.20   326.85
Z   557.0  241.4   326.85  1356.30

In [31]:
df = pd.DataFrame({
    'Name': ['Kabir', 'Meera', 'Arjun', 'Divya', 'Leo'],
    'Age': [23, 21, 24, 20, 22],
    'Score': [72, 95, 60, 88, 81]
})
print('Original:')
print(df)

Original:
    Name  Age  Score
0  Kabir   23     72
1  Meera   21     95
2  Arjun   24     60
3  Divya   20     88
4    Leo   22     81

In [32]:
print('Sort by Score ascending:')
print(df.sort_values('Score'))

Sort by Score ascending:
    Name  Age  Score
2  Arjun   24     60
0  Kabir   23     72
4    Leo   22     81
3  Divya   20     88
1  Meera   21     95

In [33]:
print('\nSort by Score descending:')
print(df.sort_values('Score', ascending=False))

Sort by Score descending:
    Name  Age  Score
1  Meera   21     95
3  Divya   20     88
4    Leo   22     81
0  Kabir   23     72
2  Arjun   24     60

In [34]:
print('\nSort by multiple columns:')
print(df.sort_values(['Age', 'Score'], ascending=[True, False]))

Sort by multiple columns:
    Name  Age  Score
3  Divya   20     88
1  Meera   21     95
4    Leo   22     81
0  Kabir   23     72
2  Arjun   24     60

In [35]:
np.random.seed(11)
df = pd.DataFrame({
    'City': ['Pune', 'Chennai', 'Pune', 'Kolkata', 'Chennai', 'Pune', 'Kolkata', 'Chennai'] * 2,
    'Dept': ['Sales', 'IT', 'Sales', 'IT', 'HR', 'HR', 'Sales', 'IT'] * 2,
    'Age': np.random.randint(22, 35, 16),
    'Salary': np.random.randint(30000, 90000, 16)
})
print('Data:')
print(df.head(10))

Data:
      City   Dept  Age  Salary
0     Pune  Sales   31   38332
1  Chennai     IT   22   89210
2     Pune  Sales   33   45397
3  Kolkata     IT   23   60197
4  Chennai     HR   29   47639
5     Pune     HR   34   37636
6  Kolkata  Sales   23   49537
7  Chennai     IT   29   72075
8     Pune  Sales   24   71368
9  Chennai     IT   30   57128

In [36]:
print(df.groupby('City').sum(numeric_only=True))

         Age  Salary
City
Chennai  156  372138
Kolkata   94  252603
Pune     190  319609

In [37]:
print(df.groupby('City').count())

         Dept  Age  Salary
City
Chennai     6    6       6
Kolkata     4    4       4
Pune        6    6       6

In [38]:
print(df.groupby('City').size())

City
Chennai    6
Kolkata    4
Pune       6
dtype: int64

In [39]:
print(df.groupby(['City', 'Dept']).mean(numeric_only=True))

                 Age    Salary
City    Dept
Chennai HR     25.50  55878.50
        IT     26.25  65095.25
Kolkata IT     22.50  61260.00
        Sales  24.50  65041.50
Pune    HR     34.00  48495.50
        Sales  30.50  55654.50

In [40]:
df1 = pd.DataFrame({'EmpID': [101, 102, 103, 104], 'Name': ['Kabir', 'Meera', 'Arjun', 'Divya']})
df2 = pd.DataFrame({'EmpID': [103, 104, 105, 106], 'Salary': [45000, 62000, 51000, 70000]})

In [41]:
print(df1)

   EmpID   Name
0    101  Kabir
1    102  Meera
2    103  Arjun
3    104  Divya

In [42]:
print(df2)

   EmpID  Salary
0    103   45000
1    104   62000
2    105   51000
3    106   70000

In [43]:
print('\n=== Inner Join (default) ===')
print(pd.merge(df1, df2, on='EmpID'))

=== Inner Join (default) ===
   EmpID   Name  Salary
0    103  Arjun   45000
1    104  Divya   62000

In [44]:
print('\n=== Left Join ===')
print(pd.merge(df1, df2, on='EmpID', how='left'))

=== Left Join ===
   EmpID   Name   Salary
0    101  Kabir      NaN
1    102  Meera      NaN
2    103  Arjun  45000.0
3    104  Divya  62000.0

In [45]:
print('\n=== Right Join ===')
print(pd.merge(df1, df2, on='EmpID', how='right'))

=== Right Join ===

   EmpID   Name  Salary
0    103  Arjun   45000
1    104  Divya   62000
2    105    NaN   51000
3    106    NaN   70000

In [46]:
print('\n=== Outer Join ===')
print(pd.merge(df1, df2, on='EmpID', how='outer'))

=== Outer Join ===
   EmpID   Name   Salary
0    101  Kabir      NaN
1    102  Meera      NaN
2    103  Arjun  45000.0
3    104  Divya  62000.0
4    105    NaN  51000.0
5    106    NaN  70000.0

In [47]:
df3 = pd.DataFrame({'Emp_Code': [101, 102, 103], 'Grade': ['A', 'B', 'C']})
print(df3)

   Emp_Code Grade
0       101     A
1       102     B
2       103     C

In [48]:
print('\nMerge on different names:')
print(pd.merge(df1, df3, left_on='EmpID', right_on='Emp_Code'))

Merge on different names:
   EmpID   Name  Emp_Code Grade
0    101  Kabir       101     A
1    102  Meera       102     B
2    103  Arjun       103     C

In [49]:
df4 = pd.DataFrame({'City': ['Pune', 'Pune', 'Chennai'], 'Year': [2022, 2023, 2022], 'Revenue': [200, 240, 150]})
df5 = pd.DataFrame({'City': ['Pune', 'Pune', 'Chennai'], 'Year': [2022, 2023, 2022], 'Expense': [140, 160, 90]})

In [50]:
print(df4)
print('df5:')
print(df5)

      City  Year  Revenue
0     Pune  2022      200
1     Pune  2023      240
2  Chennai  2022      150
df5:
      City  Year  Expense
0     Pune  2022      140
1     Pune  2023      160
2  Chennai  2022       90

In [51]:
print('\nMerge on multiple keys:')
print(pd.merge(df4, df5, on=['City', 'Year']))

Merge on multiple keys:
      City  Year  Revenue  Expense
0     Pune  2022      200      140
1     Pune  2023      240      160
2  Chennai  2022      150       90

In [52]:
df_a = pd.DataFrame({'P': [1, 2], 'Q': [3, 4]})
df_b = pd.DataFrame({'P': [9, 10], 'Q': [11, 12]})

In [53]:
print(df_a)

   P  Q
0  1  3
1  2  4

In [54]:
print(df_b)

    P   Q
0   9  11
1  10  12

In [55]:
print(pd.concat([df_a, df_b], axis=0))

    P   Q
0   1   3
1   2   4
0   9  11
1  10  12

In [56]:
print(pd.concat([df_a, df_b], axis=1))

   P  Q   P   Q
0  1  3   9  11
1  2  4  10  12

In [57]:
print(pd.concat([df_a, df_b], ignore_index=True))

    P   Q
0   1   3
1   2   4
2   9  11
3  10  12

In [58]:
# quick recap: inner, outer, left and right join in one go
for kind in ['inner', 'outer', 'left', 'right']:
    print(f'\n=== {kind.upper()} JOIN ===')
    print(pd.merge(df1, df2, on='EmpID', how=kind))

=== INNER JOIN ===

   EmpID   Name  Salary
0    103  Arjun   45000
1    104  Divya   62000

=== OUTER JOIN ===
   EmpID   Name   Salary
0    101  Kabir      NaN
1    102  Meera      NaN
2    103  Arjun  45000.0
3    104  Divya  62000.0
4    105    NaN  51000.0
5    106    NaN  70000.0

=== LEFT JOIN ===

   EmpID   Name   Salary
0    101  Kabir      NaN
1    102  Meera      NaN
2    103  Arjun  45000.0
3    104  Divya  62000.0

=== RIGHT JOIN ===
   EmpID   Name  Salary
0    103  Arjun   45000
1    104  Divya   62000
2    105    NaN   51000
3    106    NaN   70000

In [59]:
# Load a real dataset for the next part
df = pd.read_csv("neet_data.csv")

In [60]:
# Show column information and total rows/columns
print(df.info())
print('\nTotal rows:', df.shape[0])
print('Total columns:', df.shape[1])

<class 'pandas.DataFrame'>
RangeIndex: 47381 entries, 0 to 47380
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           47381 non-null  str
 1   retweet_count        47381 non-null  int64
 2   source               47362 non-null  str
 3   user_id              47381 non-null  int64
 4   user_name            47380 non-null  str
 5   user_description     36510 non-null  str
 6   user_follower_count  47381 non-null  int64
 7   user_friends_count   47381 non-null  int64
 8   user_location        26247 non-null  str
 9   user_verified        47381 non-null  bool
 10  user_url             9280 non-null   str
 11  tweet                47381 non-null  str
 12  length_of_tweet      47381 non-null  int64
dtypes: bool(1), int64(5), str(7)
memory usage: 4.4 MB
None

Total rows: 47381
Total columns: 13

In [61]:
# Sort the dataset with highest retweet to lowest
df_sorted = df.sort_values('retweet_count', ascending=False)
df_sorted.head()

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
32860,2020-11-08 05:30:01,614304,Twitter for iPhone,1024658968394625024,\xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3,\xe3\x85\xa4\xe3\x82\xa2\xe3\x82\xa4\xe3\x82\x...,62,115,NaN,False,https://t.co/cHZdP4uOdu,"RT @JoeBiden: America, I\xe2\x80\x99m honored ...",140
33262,2020-11-07 21:52:54,581097,Twitter for Android,1099388669448867842,Neet\xf0\x9f\x83\x8fPeet,\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\x...,11,141,NaN,False,NaN,"RT @KamalaHarris: We did it, @JoeBiden. https:...",63
35111,2020-11-06 14:20:33,381458,Twitter Web App,2578241503,\xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x91\xe3\x81\x...,Kei|20\xe2\x86\x91|intp|eng/fil OK|SparQlew\xe...,624,527,read carrd before follow!!,False,https://t.co/XgmHbPUgAi,RT @GretaThunberg: So ridiculous. Donald must ...,140
32585,2020-11-08 07:19:02,204348,Twitter for iPhone,1103362192169189376,Parneet kaur,"\xf0\x9f\x96\x95 all negative , all positive v...",587,193,"New Jersey, USA",False,https://t.co/PXgYJf0gIA,RT @Al_Sanchino: It\xe2\x80\x99s wild Trump su...,140
38044,2020-11-04 18:19:13,192350,Twitter for iPhone,54249914,Couture_Neet,snapchat . Neetsobeautiful,547,1182,Miii Casaa,False,NaN,"RT @JoeBiden: Keep the faith, guys. We\xe2\x80...",57

In [62]:
# Show the tweet source, count, user_name, tweet, created_at and user_url for the highest retweet count
top_row = df_sorted.iloc[0]
top_row[['source', 'retweet_count', 'user_name', 'tweet', 'created_at', 'user_url']]

source                                          Twitter for iPhone
retweet_count                                               614304
user_name                     \xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3
tweet            RT @JoeBiden: America, I\xe2\x80\x99m honored ...
created_at                                     2020-11-08 05:30:01
user_url                                   https://t.co/cHZdP4uOdu
Name: 32860, dtype: object

In [63]:
# Top 10 retweet count values, printed with a heading
top10_sum = df_sorted.head(10)['retweet_count'].sum()
print(f'TOP 10 Retweet sum is {top10_sum}')
df_sorted.head(10)[['user_name', 'retweet_count']]

TOP 10 Retweet sum is 2652225

                                               user_name  retweet_count
32860               \xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3         614304
33262                           Neet\xf0\x9f\x83\x8fPeet         581097
35111  \xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x91\xe3\x81\x...         381458
32585                                       Parneet kaur         204348
38044                                       Couture_Neet         192350
16277                           \xeb\x8b\x88\xed\x8a\xb8         137480
37849                              NEET Hime\xe2\x9c\xa8         137374
37071                           \xe3\x81\xbd\xe3\x81\x93         137367
37640   \xed\x9e\x9b\xed\x82\xa4\xeb\x8b\x88\xed\x8a\xb8         137367
14527                                             kalats         129080

In [64]:
# Count and sum of retweets done via Twitter for Android
android_tweets = df[df['source'] == 'Twitter for Android']
print('Total tweets from Twitter for Android:', android_tweets.shape[0])
print('Sum of retweet_count from Twitter for Android:', android_tweets['retweet_count'].sum())

Total tweets from Twitter for Android: 28850
Sum of retweet_count from Twitter for Android: 9386742

In [65]:
# Username and location of the person with the highest follower count
top_follower = df.loc[df['user_follower_count'].idxmax()]
print('User:', top_follower['user_name'])
print('Location:', top_follower['user_location'])

User: NDTV
Location: India

In [66]:
# New column with follower to friends ratio
df['followers_friend_ratio'] = df['user_follower_count'] / df['user_friends_count']
df[['user_name', 'user_follower_count', 'user_friends_count', 'followers_friend_ratio']].head()

,user_name,user_follower_count,user_friends_count,followers_friend_ratio
0,Rumi,14,180,0.077778
1,Tom Bewick,2314,3002,0.770819
2,Lemonade,285,1013,0.281343
3,The Rus,147,467,0.314775
4,Sakshi Yadav,2,24,0.083333

In [67]:
# Total null values in each column
df.isnull().sum()

created_at                    0
retweet_count                 0
source                       19
user_id                       0
user_name                     1
user_description          10871
user_follower_count           0
user_friends_count            0
user_location             21134
user_verified                 0
user_url                  38101
tweet                         0
length_of_tweet               0
followers_friend_ratio      147
dtype: int64

In [68]:
# Fill user_description with 'Twitter user' where it is NA
df['user_description'] = df['user_description'].fillna('Twitter user')
df['user_description'].isnull().sum()

np.int64(0)

In [69]:
# Drop all columns that have any null values
df.dropna(axis=1, inplace=True)
df.columns

Index(['created_at', 'retweet_count', 'user_id', 'user_description',
       'user_follower_count', 'user_friends_count', 'user_verified', 'tweet',
       'length_of_tweet'],
      dtype='str')

In [70]:
# Create a new column at the 3rd position named is_allow, set to True
df.insert(2, 'is_allow', True)
df.head()

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,True,1250294694937915394,Twitter user,14,180,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,True,57059492,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,True,1016022678,"Wisdom is knowing the right path to take, Inte...",285,1013,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,True,1085818329816883201,Twitter user,147,467,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,True,1227501071490113537,it's not my attitude it's my style,2,24,False,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140

In [71]:
# Drop the user_url column (no longer needed for this analysis)
df.drop(columns=['user_url'], inplace=True, errors='ignore')
df.columns

Index(['created_at', 'retweet_count', 'is_allow', 'user_id',
       'user_description', 'user_follower_count', 'user_friends_count',
       'user_verified', 'tweet', 'length_of_tweet'],
      dtype='str')