###### Feature Transformation practice
# 1. Binning -> numerical -> categorical

# Encoding
    Changing text or categories into numbers so that machines can understand and use them in models.
    Computers can't understand words like "Small", "Blue", or "Graduate" directly.
    They only understand numbers like 0, 1, ...
* categorical -> numeric
* 5 types of encoding practiced below:
  * One Hot encoding
  * Most Frequent encoding
  * Target encoding
  * Label encoding
  * Ordinal encoding

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Small laptop dataset built by hand instead of loading a csv
data = {
    'brand': ['Dell', 'HP', 'Dell', 'Lenovo', 'Apple', 'HP', 'Lenovo', 'Dell', 'Apple', 'HP'],
    'ram_type': ['DDR4', 'DDR4', 'DDR5', 'DDR4', 'DDR5', 'DDR4', 'DDR5', 'DDR4', 'DDR5', np.nan],
    'touchscreen': ['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', np.nan, 'No', 'Yes'],
    'rating': ['Average', 'Good', 'Excellent', 'Good', 'Excellent', 'Average', 'Good', 'Good', 'Excellent', 'Average'],
    'price': [45000, 38000, 62000, 41000, 95000, 36000, 43000, 44000, 98000, 35000]
}
a = pd.DataFrame(data)
a.head()

    brand ram_type touchscreen     rating  price
0    Dell     DDR4         Yes    Average  45000
1      HP     DDR4          No       Good  38000
2    Dell     DDR5          No  Excellent  62000
3  Lenovo     DDR4         Yes       Good  41000
4   Apple     DDR5          No  Excellent  95000

In [3]:
a['ram_type'].value_counts()

ram_type
DDR4    5
DDR5    4
Name: count, dtype: int64

In [4]:
b = pd.get_dummies(a['ram_type'])
b.head()

    DDR4   DDR5
0   True  False
1   True  False
2  False   True
3   True  False
4  False   True

In [5]:
b = b.astype(int)
b.head()

   DDR4  DDR5
0     1     0
1     1     0
2     0     1
3     1     0
4     0     1

### 1. OneHotEncoding
##### Creates a separate column for each category with 1s and 0s.
##### Example:
##### "DDR4" -> [1, 0], "DDR5" -> [0, 1]
##### Use when: You have non-ordered categories like brand, ram type, city.

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
one = OneHotEncoder(sparse_output=False, drop=None)
one

OneHotEncoder(sparse_output=False)

In [8]:
new_ohe = one.fit_transform(a[['ram_type']].fillna('Unknown'))
new_ohe

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
ram_data_a = pd.DataFrame(new_ohe, columns=one.get_feature_names_out(['ram_type']))
ram_data_a

   ram_type_DDR4  ram_type_DDR5  ram_type_Unknown
0            1.0            0.0               0.0
1            1.0            0.0               0.0
2            0.0            1.0               0.0
3            1.0            0.0               0.0
4            0.0            1.0               0.0
5            1.0            0.0               0.0
6            0.0            1.0               0.0
7            1.0            0.0               0.0
8            0.0            1.0               0.0
9            0.0            0.0               1.0

In [10]:
a_ohe = pd.concat([a.drop('ram_type', axis=1), ram_data_a], axis=1)
a_ohe

,brand,touchscreen,rating,price,ram_type_DDR4,ram_type_DDR5,ram_type_Unknown
0,Dell,Yes,Average,45000,1.0,0.0,0.0
1,HP,No,Good,38000,1.0,0.0,0.0
2,Dell,No,Excellent,62000,0.0,1.0,0.0
3,Lenovo,Yes,Good,41000,1.0,0.0,0.0
4,Apple,No,Excellent,95000,0.0,1.0,0.0
5,HP,Yes,Average,36000,1.0,0.0,0.0
6,Lenovo,No,Good,43000,0.0,1.0,0.0
7,Dell,NaN,Good,44000,1.0,0.0,0.0
8,Apple,No,Excellent,98000,0.0,1.0,0.0
9,HP,Yes,Average,35000,0.0,0.0,1.0

In [11]:
a_ohe.filter(like='ram_type').head()

   ram_type_DDR4  ram_type_DDR5  ram_type_Unknown
0            1.0            0.0               0.0
1            1.0            0.0               0.0
2            0.0            1.0               0.0
3            1.0            0.0               0.0
4            0.0            1.0               0.0

### 2. MostFrequentEncoding
* categories col. mein missing values ho to use karte hain.
* used for imputation (fill, replace and missing value handling)
##### Fills missing category values with the most common value.
##### Example: If "No" appears the most, missing values become "No".

In [12]:
a['touchscreen'].value_counts()

touchscreen
No     5
Yes    4
Name: count, dtype: int64

In [13]:
a.isnull().sum()

brand          0
ram_type       1
touchscreen    1
rating         0
price          0
dtype: int64

In [14]:
a.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   brand        10 non-null     str
 1   ram_type     9 non-null      str
 2   touchscreen  9 non-null      str
 3   rating       10 non-null     str
 4   price        10 non-null     int64
dtypes: int64(1), str(4)
memory usage: 532.0 bytes

In [15]:
most_frq_value = a['touchscreen'].mode()[0]
most_frq_value

'No'

In [16]:
# fill missing value with the most frequent value
a_most_frequent = a.copy()
a_most_frequent['touchscreen'] = a_most_frequent['touchscreen'].fillna(most_frq_value)
a_most_frequent

    brand ram_type touchscreen     rating  price
0    Dell     DDR4         Yes    Average  45000
1      HP     DDR4          No       Good  38000
2    Dell     DDR5          No  Excellent  62000
3  Lenovo     DDR4         Yes       Good  41000
4   Apple     DDR5          No  Excellent  95000
5      HP     DDR4         Yes    Average  36000
6  Lenovo     DDR5          No       Good  43000
7    Dell     DDR4          No       Good  44000
8   Apple     DDR5          No  Excellent  98000
9      HP      NaN         Yes    Average  35000

In [17]:
a_most_frequent['touchscreen'].head()

0    Yes
1     No
2     No
3    Yes
4     No
Name: touchscreen, dtype: str

### 3. TargetEncoding
* High cardinality (many unique values)
##### Replaces a category with the average of the target variable for that category.
##### Example: If "Apple" laptops average price is 96500, "Apple" becomes 96500.

In [18]:
a.head()

    brand ram_type touchscreen     rating  price
0    Dell     DDR4         Yes    Average  45000
1      HP     DDR4          No       Good  38000
2    Dell     DDR5          No  Excellent  62000
3  Lenovo     DDR4         Yes       Good  41000
4   Apple     DDR5          No  Excellent  95000

In [19]:
brand_mean = a.groupby('brand')['price'].mean()
brand_mean

brand
Apple     96500.000000
Dell      50333.333333
HP        36333.333333
Lenovo    42000.000000
Name: price, dtype: float64

In [20]:
a['brand_encoded'] = a['brand'].map(brand_mean)
a.head()

    brand ram_type touchscreen     rating  price  brand_encoded
0    Dell     DDR4         Yes    Average  45000   50333.333333
1      HP     DDR4          No       Good  38000   36333.333333
2    Dell     DDR5          No  Excellent  62000   50333.333333
3  Lenovo     DDR4         Yes       Good  41000   42000.000000
4   Apple     DDR5          No  Excellent  95000   96500.000000

### 4. LabelEncoding
##### Turns each category into a number (like 0, 1, 2...).
##### Example: "Dell" -> 0, "HP" -> 1, "Lenovo" -> 2
##### Use when: Categories are names, and there's no order.

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()

In [23]:
a['brand'].value_counts()

brand
Dell      3
HP        3
Lenovo    2
Apple     2
Name: count, dtype: int64

In [24]:
a['brand_label'] = le.fit_transform(a['brand'])
a

    brand ram_type touchscreen     rating  price  brand_encoded  brand_label
0    Dell     DDR4         Yes    Average  45000   50333.333333            1
1      HP     DDR4          No       Good  38000   36333.333333            2
2    Dell     DDR5          No  Excellent  62000   50333.333333            1
3  Lenovo     DDR4         Yes       Good  41000   42000.000000            3
4   Apple     DDR5          No  Excellent  95000   96500.000000            0
5      HP     DDR4         Yes    Average  36000   36333.333333            2
6  Lenovo     DDR5          No       Good  43000   42000.000000            3
7    Dell     DDR4         NaN       Good  44000   50333.333333            1
8   Apple     DDR5          No  Excellent  98000   96500.000000            0
9      HP      NaN         Yes    Average  35000   36333.333333            2

In [25]:
print(dict(zip(le.classes_, le.transform(le.classes_))))

{'Apple': np.int64(0), 'Dell': np.int64(1), 'HP': np.int64(2), 'Lenovo': np.int64(3)}

In [26]:
print(a[['brand', 'brand_label']].head(10))

    brand  brand_label
0    Dell            1
1      HP            2
2    Dell            1
3  Lenovo            3
4   Apple            0
5      HP            2
6  Lenovo            3
7    Dell            1
8   Apple            0
9      HP            2

### 5. OrdinalEncoding
##### Turns ordered categories into numbers based on rank.
##### Example: "Average" -> 0, "Good" -> 1, "Excellent" -> 2
##### Use when: Categories have a meaningful order.

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [28]:
a['rating'].value_counts()

rating
Good         4
Average      3
Excellent    3
Name: count, dtype: int64

In [29]:
rating_order = [['Average', 'Good', 'Excellent']]

In [30]:
ord_enc = OrdinalEncoder(categories=rating_order)
ord_enc

OrdinalEncoder(categories=[['Average', 'Good', 'Excellent']])

In [31]:
a['rating_encoded'] = ord_enc.fit_transform(a[['rating']])
a

,brand,ram_type,touchscreen,rating,price,brand_encoded,brand_label,rating_encoded
0,Dell,DDR4,Yes,Average,45000,50333.333333,1,0.0
1,HP,DDR4,No,Good,38000,36333.333333,2,1.0
2,Dell,DDR5,No,Excellent,62000,50333.333333,1,2.0
3,Lenovo,DDR4,Yes,Good,41000,42000.000000,3,1.0
4,Apple,DDR5,No,Excellent,95000,96500.000000,0,2.0
5,HP,DDR4,Yes,Average,36000,36333.333333,2,0.0
6,Lenovo,DDR5,No,Good,43000,42000.000000,3,1.0
7,Dell,DDR4,NaN,Good,44000,50333.333333,1,1.0
8,Apple,DDR5,No,Excellent,98000,96500.000000,0,2.0
9,HP,NaN,Yes,Average,35000,36333.333333,2,0.0

In [32]:
print(a[['rating', 'rating_encoded']].head(10))

      rating  rating_encoded
0    Average             0.0
1       Good             1.0
2  Excellent             2.0
3       Good             1.0
4  Excellent             2.0
5    Average             0.0
6       Good             1.0
7       Good             1.0
8  Excellent             2.0
9    Average             0.0

# Binning
#### Binning means:
##### Putting numbers into groups or buckets.
##### Imagine you have laptop prices. Instead of the exact number like 44000 or 95000, group them like this:
##### 0-45000 -> "Budget"
##### 45001-70000 -> "Mid-range"
##### 70001+ -> "Premium"

In [33]:
from sklearn.preprocessing import KBinsDiscretizer

# Sample data
price_data = {'Price': a['price'].tolist()}
df = pd.DataFrame(price_data)

# Create binner: 3 bins, ordinal encoding, uniform strategy
binner = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')

# Apply binning
df['Price_Binned'] = binner.fit_transform(df[['Price']])

print(df)

   Price  Price_Binned
0  45000           0.0
1  38000           0.0
2  62000           1.0
3  41000           0.0
4  95000           2.0
5  36000           0.0
6  43000           0.0
7  44000           0.0
8  98000           2.0
9  35000           0.0

In [34]:
# Binning with quantile strategy, on a slightly bigger sample
data2 = {'Screen_Hours': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20]}
df2 = pd.DataFrame(data2)

kbins = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='quantile')
df2['Screen_Hours_Binned'] = kbins.fit_transform(df2[['Screen_Hours']])
print(df2)

    Screen_Hours  Screen_Hours_Binned
0              1                  0.0
1              2                  0.0
2              3                  0.0
3              4                  0.0
4              5                  0.0
5              6                  1.0
6              7                  1.0
7              8                  1.0
8              9                  1.0
9             10                  1.0
10            12                  2.0
11            14                  2.0
12            16                  2.0
13            18                  2.0
14            20                  2.0

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [35]:
# small helper: count vowels in a string
text = "encoding practice"
vowels = "aeiouAEIOU"
count = 0
for ch in text:
    if ch in vowels:
        count += 1
print("vowels:", count)

vowels: 6

In [36]:
# sum of numbers divisible by 25 in a list
nums = [10, 25, 30, 50, 75, 90, 100]
total = 0
for n in nums:
    if n % 25 == 0:
        total += n
print("sum divisible by 25:", total)

sum divisible by 25: 250